# Detectron2 YAML – Mask R‑CNN + ResNet‑101‑FPN backbone
# Copied from COCO Mask R‑101‑FPN 3x and tuned for this homework dataset.
# Training hyper‑params match R‑50 config; adjust IMS_PER_BATCH if OOM.
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 4
SOLVER:
  IMS_PER_BATCH: 5
  BASE_LR: 0.0008
  MAX_ITER: 14000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 1000
  AMP:
    ENABLED: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 896, 1024)
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 2048
  RANDOM_FLIP: "horizontal_vertical"
  MASK_FORMAT: "bitmask"
TEST:
  EVAL_PERIOD: 1000
VERSION: 2