# Alternative hyper‑params for ablation: higher LR + Multi‑Step decay.
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 4
SOLVER:
  IMS_PER_BATCH: 6     # keep same batch size (fits 24 GB)
  BASE_LR: 0.0012      # +50 % LR for potentially faster convergence
  MAX_ITER: 16000      # train a bit longer to match decay schedule
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: [10000, 14000]
  GAMMA: 0.1
  WARMUP_FACTOR: 0.001
  CHECKPOINT_PERIOD: 1000
  AMP:
    ENABLED: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN: (256, 384, 512)  # slightly larger min size
  MAX_SIZE_TRAIN: 2500
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 2500
  RANDOM_FLIP: "horizontal_vertical"
  MASK_FORMAT: "bitmask"
TEST:
  EVAL_PERIOD: 1000
VERSION: 2

